import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
// import your Sidebar component

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-blue-50">
        <div className="flex min-h-screen">
          <main className="">{children}</main>
        </div>
      </body>
    </html>
  );
}
