import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { SidebarComponent as Sidebar }  from "../components/sidebar/Sidebar"; // import your Sidebar component

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} h-screen`}>
      <body className="flex h-full">
        <aside className="w-64 bg-background p-4 sticky top-0 h-screen">
          <Sidebar />
        </aside>
        <main className="flex-1 h-full">{children}</main>
      </body>
    </html>
  );
}
